apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: backend
    path: patch-backend-env.yaml
  - target:
      kind: Deployment
      name: backend
    path: patch-backend-resources.yaml
  - target:
      kind: Deployment
      name: frontend
    path: patch-frontend-resources.yaml
  - target:
      kind: IngressRoute
      name: fastapi-platform
    path: patch-ingressroute.yaml
