apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingressroutes.yaml
  - n8n-pvc.yaml
  - n8n-startup-configmap.yaml
  - n8n-workflow-configmap.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingressroute.yaml
